### ISSUE TITLE
Add CLI commands for OCM invitation workflow

### ISSUE THREAD

**Issue by ishank011** [cs3org/reva#1149]

**Comment by jimil749** [comment]
Hi @ishank011! I thought of giving this a shot. So just to summarize, we are required to add an `ocm-invite` command with that fetches the invite token and then forwards that token to another user, right? This could be done through the `GenerateInviteToken` and the `ForwardInvite` APIs. Is this the correct method to move forward?

**Comment by ishank011** [comment]
Hey @jimil749. Yep, that is the plan. We'll need separate commands for generating the token and forwarding the invite though, since they're expected to be executed on different mesh providers, by the originator and recipient, respectively

 https://reva.link/docs/tutorials/share-tutorial/ should give you a good idea of the workflow but it might be a bit dated, so feel free to reach out if you face any issues.

**Comment by jimil749** [comment]
@ishank011, I have got a question. I implemented the token generation command which generates an invite token. 

Now, for the next task which is to forward the token, which should be a different command (executed by the recipient) we require the generated token.  In the [doc](https://reva.link/docs/tutorials/share-tutorial/) provided, since the token generation and forwarding happens manually, we can just copy and paste the token. But I am not so sure how the recipient will get that token to make the request.

Can there be a flag (maybe `-token`) which can pass the token?

**Comment by jimil749** [comment]
Just a correction, passing just the `token` won't suffice. Since the `ForwardInviteRequest` requires the inviteToken object, which consists of the `token`, `user_id`, `expiration` and `description` fields. (`expiration` and `description` are optional)

**Comment by ishank011** [comment]
The `/invites/forward` endpoint requires two arguments, the token (just the string) and the token creator's mesh provider. You can add flags for both of these. Refer https://github.com/cs3org/reva/blob/master/internal/http/services/ocmd/invites.go#L128

**Comment by jimil749** [comment]
Ahh ok! I was looking at the gRPC endpoint! Thanks for clearing. :)

**Comment by ishank011** [comment]
No, you still need to call the GRPC endpoint, but the implementation should be similar to the reference which I sent. In the inviteToken object, you can leave the rest of the fields empty as the backend only needs the UUID.
