### ISSUE TITLE
Modularize API token management in GRAPPA drivers

### ISSUE THREAD

**Issue by ishank011** [cs3org/reva#1562]
https://github.com/cs3org/reva/tree/master/pkg/cbox/group/rest and https://github.com/cs3org/reva/tree/master/pkg/cbox/user/rest have a lot of overlapping code which can be reused.

**Comment by jimil749** [comment]
Hi @ishank011! I would like to work on this, if that's fine. So I suppose, we are to move out duplicated methods out of `user/rest.go` and `group/rest.go` into a separate file to prevent duplication?

**Comment by ishank011** [comment]
Hi @jimil749! Yep, that's precisely it. cbox has a utils package so you can move these there or create a separate one.

**Comment by jimil749** [comment]
@ishank011 I had a question. Since we have the `manager` struct and its methods repeated in the user and group package, do I need to move the entire `manager` struct (which will then implement both `user.Manager` and `group.Manager` interface) and its methods into the utils package and then call those methods from the respective packages i.e `user/rest` and `group/rest`?

**Comment by ishank011** [comment]
Having the same struct implement both the interfaces won't be a good idea as the interface methods are totally different. Let's keep them separate.
