### ISSUE TITLE
NPE if "name" or "preferred_username" is missing in oidc userinfo

### ISSUE THREAD

**Issue by IljaN** [cs3org/reva#590]
If an OIDC client has not requested the "Profile" Scope the IDP might return a reduced set of userinfo attributes:

```
 "userInfo": {
    "sub": "XtSi_miyWSB-pkvGnxPoC5A4flih0UCLgvU7cLwjmjCKX7FYn2HWk6rRCEuy2G5qAy_yMQc_FK9aNFhUMrX2pQ@konnect",
    "profile": "",
    "email": "einstein@example.org",
    "email_verified": false
  }
```
This leads to a nullpointer error when casting the values to string here:
https://github.com/cs3org/reva/blob/0dbce24f7e8b508c1ecab2d145979562888a7a76/pkg/auth/manager/oidc/oidc.go#L129

...and here:

https://github.com/cs3org/reva/blob/0dbce24f7e8b508c1ecab2d145979562888a7a76/pkg/auth/manager/oidc/oidc.go#L121

Same should be true for "email" as there is also an "email" scope.

Should I provide a PR which returns an error (as in golang error) in case this fields are missing?

**Comment by butonic** [comment]
It depends on the mapping. The oidc spec only requires the `sub` claim. But that cannot be used to look up users in an LDAP server. Furthermore, while the spec says the sub must not change in reality a user may be identified by different subs, eg. when the idp changes.

I would prefer to generate a uuid for every user and use that as the internal opaqueid for the user. That is what we plan to do for OCIS. The ocis-accounts service will be used to store the mapping of sub to uuid and a Middleware will fetch it after authentication.

If a storage driver like Eos allows writing ACLs for existing users it can do that by using the username.

The solution of using the preferred_username claim and match it to the LDAP uid attribute as well as using the email claim and matching it to the LDAP email attribute are fragile because these properties can change anytime which would break federated shares because user name != user ID.

A uuid is the proper solution IMNSHO.

The claim mapping should never throw a now though, so pr welcome.

**Comment by labkode** [comment]
@butonic it makes sense to me given that the storage drivers can expand the user uuid to a full user object (so on EOS you rely on the username)
