### ISSUE TITLE
Stat received file as the original user, not the recipient

### ISSUE THREAD

**Issue by ishank011** [cs3org/reva#737]
https://github.com/cs3org/reva/blob/3aa67e818a8d12f9ffc61daceecde612676eb8b1/internal/grpc/services/gateway/usershareprovider.go#L406-L414
When a recipient accepts a share, we create a share reference and while doing that, we stat for the shared file while logged in as the recipient. This looks for the file in the recipient's namespace, where it won't be present. Instead, we need to look for it in that user's namespace who created the share. @labkode

**Comment by labkode** [comment]
@ishank I see the issue, that's is because we are exposing only the /home namespace, on a production setup there will be /home and `/users/ishank/`,  `/users/hugo`, .. so the reference always point to `/users/X`. Pointing to `/home` won't be possible in that scenario as the `/home` namespace is special and only knows about the current logged in user.

**Comment by ishank011** [comment]
@labkode even if the resourceID points to the complete path, in the [eos driver](https://github.com/cs3org/reva/blob/master/pkg/storage/fs/eos/eos.go#L633), we anyway wrap it in the current user's path (which would be /eos/user/i/ishank/), so it would still look for it there only.

**Comment by labkode** [comment]
@ishank011 wrapping for home only occurs if the eos driver is configured to use it:
https://github.com/cs3org/reva/blob/master/pkg/storage/fs/eos/eos.go#L248

So in production, you'll have at least two EOS drivers, one exposing `/home` and other `/users`/

**Comment by ishank011** [comment]
Okay makes sense. Thanks!
